SELECT * 
FROM VERAN_BASE_DRE A 
WHERE A.DATA_ENTRADA BETWEEN '&DT1' AND '&DT2'
---------------------------------------------------------------------------------
SELECT A.NROEMPRESA,
       A.FILIAL,
       TO_CHAR(a.DATA_ENTRADA, 'DD/MM/YYYY')DATA_ENTRADA,
       TO_CHAR(A.DATA_EMISSAO, 'DD/MM/YYYY')DATA_EMISSAO,
       A.CENTRO_CUSTO_COD,
       A.CENTRO_CUSTO,
       A.CONTA_CONTABIL,
       A.NATUREZA_COD,
       A.NATUREZA,
       A.SEQPESSOA,
       A.CPFCNPJ, 
       A.PESSOA,
       A.NRONOTA,
       A.VALOR,
       TRIM(REPLACE(REPLACE(A.OBSERVACAO,CHR(10),' '), CHR(13),' '))OBSERVACAO,
       A.USUARIO,
       A.SITUACAO,
       A.LINKERP,
       A.VLRINSS,
       A.VLRIR,
       A.VLRISSST,
       A.VLRPIS,
       A.VLRCOFINS,
       A.VLRCSSLL,
       A.VLRSESTSENAT,
       A.VLRISS,
       A.VLRISENTO,
       A.VLRICMSOUTRAS,
       A.VLRICMS,
       A.VLRIPI,
       A.VLROUTROSIPI,
       A.VLRISENTOIPI,
       A.VLRCOFINSCRED,
       A.VLRPISCRED,
       A.NFECHAVEACESSO
       
  FROM VERAN_BASE_DRE A
 WHERE A.DATA_ENTRADA BETWEEN '&DT1' AND '&DT2'
 
 UNION ALL
 
/*  A CONSULTA ABAIXO RETORNA APENAS A NAT 2700 DEVIDO AOS LANÇAMENTOS NÃO REALIZAREM RATEIO E A FALTA DE PREENCHIMENTO NA ABA "CONTABILIZAÇÃO FISCAL" 
NÃO GRAVA AS INFORMAÇÕES NA TABELA OR_NFPLANILHALANCTO B,  */

SELECT A.NROEMPRESA,
       A.NROEMPRESA FILIAL,   
       TO_CHAR(A.DTAENTRADA, 'DD/MM/YYYY')DATA_ENTRADA,
       TO_CHAR(A.DTAEMISSAO, 'DD/MM/YYYY')DATA_EMISSAO,
       TO_NUMBER(DECODE(A.NROEMPRESA, 12, '1001', 2, '1002', 3, '1003', 5, '1005', 6, '1006', 7, '1007', 8, '1008',  9, '1009', 10, '1010', 11, '1013', 32, '1014', 33, '1015', 34, '1016'))  CENTRO_CUSTO_COD,
       DECODE(A.NROEMPRESA, 12,'Loja 1', 2, 'Loja 2', 3, 'Loja 3', 5, 'Loja 5', 6, 'Loja 6', 7, 'Loja 7', 8, 'Loja 8',  9, 'Loja 9', 10, 'Loja 10', 11, 'Loja 11', 32, 'loja 12', 33, 'LOJA 13 POÁ', 34, 'LOJA 14 MOGI') CENTRO_CUSTO,
       B.CONTADEBITO CONTA_CONTABIL,   ---
       A.CODHISTORICO NATUREZA_COD,
       INITCAP(C.DESCRICAO) NATUREZA,
       A.SEQPESSOA,
       CASE
         WHEN F.FISICAJURIDICA = 'F' THEN
          LPAD(F.NROCGCCPF, 9, 0) || LPAD(F.DIGCGCCPF, 2, 0)
         ELSE
          LPAD(F.NROCGCCPF, 12, 0) || LPAD(F.DIGCGCCPF, 2, 0)
       END CPFCNPJ,
       INITCAP(F.NOMERAZAO) PESSOA,
       A.NRONOTA,
       A.VALOR, 
       A.OBSERVACAO OBSERVACAO,
       A.USUALTERACAO USUARIO,
       A.SITUACAO,
       A.LINKERP,
       A.VLRINSS,
       A.VLRIR,
       A.VLRISSST,
       A.VLRPIS,
       A.VLRCOFINS,
       A.VLRCSSLL,
       A.VLRSESTSENAT,
       A.VLRISS,
       A.VLRISENTO,
       A.VLROUTRAS VLRICMSOUTRAS,
       A.VLRICMS,
       A.VLRIPI,
       A.VLROUTROSIPI,
       A.VLRISENTOIPI,
       A.VLRCOFINSCRED,
       A.VLRPISCRED,
       A.NFECHAVEACESSO

  FROM OR_NFDESPESA        A, 
       OR_NFPLANILHALANCTO B,
       CT_HISTORICO        C,
       CTV_CENTROCUSTO     D,
       GE_EMPRESA          E,
       GE_PESSOA           F
 WHERE A.CODHISTORICO = C.CODHISTORICO
      
   AND A.NROEMPRESAORC = C.NROEMPRESA
   AND A.SEQNOTA = B.SEQNOTA(+)
   AND A.NROEMPRESA = E.NROEMPRESA
   AND A.SEQPESSOA = F.SEQPESSOA(+)
   AND B.CENTROCUSTODB = D.CENTROCUSTO(+)
   AND B.NROEMPRESA = D.NROEMPRESA(+)
   AND c.CODHISTORICO = 2700
   AND A.DTAENTRADA BETWEEN '&DT1' AND '&DT2';
  
