select MGC_CONTRATOCATEGORIA.*, MGC_CONTRATOCATEGORIA.SEQIDENTIFICADOR, MGC_CONTRATOCATEGORIA.SEQCATEGORIA, MGC_CONTRATOCATEGORIA.NRODIVISAO                                                                                                                                                                                                               
from MGC_CONTRATOCATEGORIA
where  SEQIDENTIFICADOR = '66159'                                                          
order by SEQCATEGORIA  


select  MGC_CONTRATOFAMILIA.*, MGC_CONTRATOFAMILIA.SEQIDENTIFICADOR, MGC_CONTRATOFAMILIA.SEQFAMILIA, MGC_CONTRATOFAMILIA.NRODIVISAO                                                                                                                                                                                                   
from MGC_CONTRATOFAMILIA
where SEQIDENTIFICADOR = '66159'                                                         
order by SEQFAMILIA  

SELECT * FROM MGC_CONTRATODESCONTO G
SELECT * FROM MAP_FAMILIA
WHERE SEQFAMILIA IN (164330)

select * FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATODESCONTO G
WHERE F.SEQIDENTIFICADOR = G.SEQCONTRATODESCONTO



SELECT * FROM MGC_CONTRATODESCONTO G  ---
WHERE G.SEQCONTRATO = '7177' 

SELECT * FROM MGC_CONTRATO H
WHERE H.SEQCONTRATO = '7177'


select * FROM MGC_CONTRATORETORNO I
WHERE i.SEQCONTRATO = '6715'

select * FROM MGC_CONTRATOCRES J
WHERE j.SEQCONTRATO = '6715'

select * FROM MGC_CONTRATONIVELSERV L

select * FROM MGC_CONTRATOSAZONAL M

select * FROM MGC_CONTRATOFAMILIAEX F

select * FROM MGC_CONTRATOEVENTO K
WHERE k.SEQCONTRATO = '6715'



     SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO,NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') COMPRADOR,
 H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATODESCONTO G, MGC_CONTRATO H , MAP_FAMILIA M 
        WHERE G.SEQCONTRATO = H.SEQCONTRATO
         AND F.SEQIDENTIFICADOR  = G.SEQCONTRATODESCONTO
         AND F.SEQFAMILIA = M.SEQFAMILIA
      --   AND NVL(F.SEQFAMILIA,0) = 0
         AND H.STATUS = 'A'
          AND G.SEQCONTRATO IN (7177)  
         
      SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR')  COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATODESCONTO  G, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR(+) = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA(+)
          AND NVL(F.SEQFAMILIA,0) = 0
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (&COMPRADOR) 
         
         

------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------- CONTRATOS DE FIDELIDADE COM SEQFAMILIA -------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------


     SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, G.PERCDESCONTO,NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') COMPRADOR,
 H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS, 'SEM' EXCECOES
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATODESCONTO G, MGC_CONTRATO H , MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(G.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (&COMPRADOR)
         AND G.SEQCONTRATO IN (7177)
          
          
           UNION ALL
           
           SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, G.PERCDESCONTO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') COMPRADOR,
 H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'SEM' EXCECOES
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATODESCONTO G, MGC_CONTRATO H , MAP_FAMILIA M 
        WHERE G.SEQCONTRATO = H.SEQCONTRATO
         AND F.SEQIDENTIFICADOR(+)  = G.SEQCONTRATODESCONTO
         AND F.SEQFAMILIA = M.SEQFAMILIA(+)
         AND NVL(F.SEQFAMILIA,0) = 0
         AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS) 
         AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (&COMPRADOR)   
        
         
           UNION ALL    
           
       SELECT F.SEQFAMILIA, M.FAMILIA, I.SEQCONTRATO, I.DESCRICAO, I.PERCDESCONTO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS, 'SEM' EXCECOES
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATORETORNO I, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR(+) = I.SEQCONTRATORETORNO
          AND I.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA(+)
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (&COMPRADOR)

       UNION ALL
       
      SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, G.PERCDESCONTO, (SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR) COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'COM' EXCECOES
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATODESCONTO  G, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (&COMPRADOR)
         
        UNION ALL /* 
        
              SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR')  COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'COM' EXCECOES
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATODESCONTO  G, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR(+) = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA(+)
          AND NVL(F.SEQFAMILIA,0) = 0
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (&COMPRADOR) 
             
       UNION ALL*/
       
       SELECT F.SEQFAMILIA, M.FAMILIA, I.SEQCONTRATO, I.DESCRICAO, I.PERCDESCONTO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR')  COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'COM' EXCECOES
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATORETORNO I, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR(+) = I.SEQCONTRATORETORNO
          AND I.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA(+)
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR')  IN (&COMPRADOR)
       
         ORDER BY 2, 3, 4



------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------- CONTRATOS DE FIDELIDADE COM SEQFAMILIA ----------VERSÃO PUBLICADA 09/04/2024 -----------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------------


     SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, G.PERCDESCONTO, (SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR) COMPRADOR,
 H.SEQPESSOACAF, H.DESCRICAO, TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS, 'SEM' EXCECOES
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATODESCONTO G, MGC_CONTRATO H , MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
         AND NVL(G.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND (SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR) IN (#LS2)
       
           UNION ALL
           
           SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, G.PERCDESCONTO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') COMPRADOR,
 H.SEQPESSOACAF, H.DESCRICAO, TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'SEM' EXCECOES
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATODESCONTO G, MGC_CONTRATO H , MAP_FAMILIA M 
        WHERE G.SEQCONTRATO = H.SEQCONTRATO
         AND F.SEQIDENTIFICADOR(+)  = G.SEQCONTRATODESCONTO
         AND F.SEQFAMILIA = M.SEQFAMILIA(+)
         AND NVL(F.SEQFAMILIA,0) = 0
         AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
         AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (#LS2)
           
           UNION ALL    
           
       SELECT F.SEQFAMILIA, M.FAMILIA, I.SEQCONTRATO, I.DESCRICAO, I.PERCDESCONTO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO,TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS, 'SEM' EXCECOES
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATORETORNO I, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR(+) = I.SEQCONTRATORETORNO
          AND I.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA(+)
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (#LS2)

       UNION ALL
       
      SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, G.PERCDESCONTO, (SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR) COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO,TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'COM' EXCECOES
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATODESCONTO  G, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (#LS2)
         
        UNION ALL /* 
        
              SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR')  COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, H.DTAINICIOVALIDADE, H.DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'COM' EXCECOES
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATODESCONTO  G, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR(+) = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA(+)
          AND NVL(F.SEQFAMILIA,0) = 0
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (&STATUS)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = G.SEQCOMPRADOR ), 'SEM COMPRADOR') IN (&COMPRADOR) 
             
       UNION ALL*/
       
       SELECT F.SEQFAMILIA, M.FAMILIA, I.SEQCONTRATO, I.DESCRICAO, I.PERCDESCONTO, NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR')  COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO,TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS , 'COM' EXCECOES
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATORETORNO I, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR(+) = I.SEQCONTRATORETORNO
          AND I.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA(+)
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND NVL((SELECT APELIDO FROM MAX_COMPRADOR C WHERE C.SEQCOMPRADOR = I.SEQCOMPRADOR ), 'SEM COMPRADOR')  IN (#LS2)
         
         ORDER BY 2, 3, 4












------------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------- CONTRATOS DE FIDELIDADE COM SEQFAMILIA --------- VERSÃO PUBLICADA 08/04/2024 ---- 1º BACKUP 09/04 --------
------------------------------------------------------------------------------------------------------------------------------------------------------------

ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

     SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, DECODE(G.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
 H.SEQPESSOACAF, H.DESCRICAO, TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATODESCONTO G, MGC_CONTRATO H , MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(G.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(G.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
           UNION ALL
       SELECT F.SEQFAMILIA, M.FAMILIA, I.SEQCONTRATO, I.DESCRICAO, DECODE(I.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATORETORNO I, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = I.SEQCONTRATORETORNO
          AND I.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(I.INDDESCGERAL, 'N') = 'N'
          AND H.SEQCONTRATO = '7183'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(I.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
          UNION ALL
       SELECT F.SEQFAMILIA,  M.FAMILIA, J.SEQCONTRATO, J.DESCRICAO, DECODE (J.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO,  TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATOCRES J, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = J.SEQCONTRATOCRES
          AND J.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(J.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(J.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
       UNION ALL
       SELECT F.SEQFAMILIA, M.FAMILIA, L.SEQCONTRATO, L.DESCRICAO, DECODE(L.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO, TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIA   F, MGC_CONTRATONIVELSERV L, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = L.SEQCONTRATONIVELSERV
          AND L.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(L.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(L.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
       UNION ALL
       SELECT F.SEQFAMILIA, M.FAMILIA, NULL SEQCONTRATO, NULL DESCRICAO, NULL SEQCOMPRADOR, H.SEQPESSOACAF, H.DESCRICAO, TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIA F, MGC_CONTRATOSAZONAL M, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = M.SEQCONTRATOSAZONAL
          AND M.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(M.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
       UNION ALL
       SELECT F.SEQFAMILIA, M.FAMILIA, G.SEQCONTRATO, G.DESCRICAO, DECODE(G.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO,  TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATODESCONTO  G, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = G.SEQCONTRATODESCONTO
          AND G.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(G.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(G.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
       UNION ALL
       SELECT F.SEQFAMILIA, M.FAMILIA, I.SEQCONTRATO, I.DESCRICAO, DECODE(I.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO,  TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATORETORNO I, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = I.SEQCONTRATORETORNO
          AND I.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(I.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(I.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
       UNION ALL
       SELECT F.SEQFAMILIA, M.FAMILIA, J.SEQCONTRATO, J.DESCRICAO, DECODE(J.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
        H.SEQPESSOACAF, H.DESCRICAO,  TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATOCRES J, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = J.SEQCONTRATOCRES
          AND J.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(J.INDDESCGERAL, 'N') = 'N'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(J.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
       UNION ALL
       SELECT F.SEQFAMILIA, M.FAMILIA, NULL SEQCONTRATO, NULL DESCRICAO, NULL SEQCOMPRADOR, H.SEQPESSOACAF, H.DESCRICAO, TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATOEVENTO K, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = K.SEQCONTRATOEVENTO
          AND K.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
       UNION ALL
         SELECT F.SEQFAMILIA, M.FAMILIA, L.SEQCONTRATO, L.DESCRICAO, DECODE(L.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') COMPRADOR,
          H.SEQPESSOACAF, H.DESCRICAO,  TO_CHAR(H.DTAINICIOVALIDADE,'DD/MM/YYYY')DTAINICIOVALIDADE, TO_CHAR(H.DTAFIMVALIDADE,'DD/MM/YYYY')DTAFIMVALIDADE, DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') STATUS 
         FROM MGC_CONTRATOFAMILIAEX F, MGC_CONTRATONIVELSERV L, MGC_CONTRATO H, MAP_FAMILIA M
        WHERE F.SEQIDENTIFICADOR = L.SEQCONTRATONIVELSERV
          AND L.SEQCONTRATO = H.SEQCONTRATO
          AND F.SEQFAMILIA = M.SEQFAMILIA
          AND NVL(L.INDDESCGERAL, 'N') = 'N'
          AND H.SEQCONTRATO = '7183'
          AND DECODE(H.STATUS, 'A', 'ATIVO', 'I', 'INATIVO') IN (#LS1)
          AND DECODE(L.SEQCOMPRADOR,42,'KLEBER',15,'RODRIGO',17,'EDER',44,'JOSE LUCAS',46,'TATIELLE',32,'RENAN',40,'LEANDRO',47,'FELIPE FERRARI',48,'LUCAS RIBEIRO',51,'EVELIN ALEXIA',52,'MARCELO',53,'LEONARDO') IN (#LS2)
                   
         ORDER BY 3, 4
