-----------------------------------------------------------------------------------------------
-------------------------------  MOVIMENTOS DE TITULOS OBRIGACAO --------- em faze de teste ---
-----------------------------------------------------------------------------------------------

Select MAX(FI_TITULO.NROEMPRESA)NROEMPRESA,
       GE_PESSOA.NOMERAZAO PESSOA,
       GE_PESSOA.SEQPESSOA,
       SUBSTR(FC5MASKCNPJCPF(GE_PESSOA.NROCGCCPF,
                             GE_PESSOA.DIGCGCCPF,
                             GE_PESSOA.FISICAJURIDICA),
              1,
              20)CNPJ_CPF,
    --   MAX(FI_TITOPERACAO.USUALTERACAO)USUALTERACAO,   
       MAX(FI_TITULO.NROTITULO)NROTITULO,
       MAX(FI_TITULO.CODESPECIE)CODESPECIE,
     --  MAX(TO_CHAR(FI_TITOPERACAO.DTAOPERACAO, 'DD/MM/YYYY'))DTAOPERACAO,
       MAX(TO_CHAR(FI_TITOPERACAO.DTACONTABILIZA, 'DD/MM/YYYY'))DTACONTABILIZACAO,
      -- MAX(TO_CHAR(FI_TITOPERACAO.DTAALTERACAO, 'DD/MM/YYYY'))DTAALTERACAO,   
       MAX(TO_CHAR(FI_TITULO.DTAVENCIMENTO, 'DD/MM/YYYY'))DTAVENCIMENTO,      
       MAX(TO_CHAR(FI_TITULO.DTAQUITACAO, 'DD/MM/YYYY'))DTAQUITACAO,
       MAX(TO_CHAR(FI_TITULO.DTAPROGRAMADA, 'DD/MM/YYYY'))DTAPROGRAMADA, 
       MAX(FI_TITULO.VLRNOMINAL)VLRNOMINAL,                        
       NVL(PAGTO_TROCA.DTAOPERACAO, NULL),
       NVL(PAGTO_TROCA.vlroperacao,0),
       NVL(DESC_LOGISTICA.DTAOPERACAO,NULL),
       NVL(DESC_LOGISTICA.vlroperacao, 0),
       NVL(DESC_FIDEL.DTAOPERACAO,NULL),
       NVL(DESC_FIDEL.vlroperacao,0),
       NVL(DESC_ANIVER.DTAOPERACAO,NULL),
       NVL(DESC_ANIVER.vlroperacao,0),
       NVL(DESC_INAUG.DTAOPERACAO,NULL),
       NVL(DESC_INAUG.vlroperacao,0),
       NVL(INTR_PRODUTO.DTAOPERACAO,NULL),
       NVL(INTR_PRODUTO.vlroperacao,0),
       NVL(DESC_MARKETING.DTAOPERACAO,NULL),
       NVL(DESC_MARKETING.vlroperacao,0),
       NVL(DESC_TABLOIDE.DTAOPERACAO,NULL),
       NVL(DESC_TABLOIDE.vlroperacao,0),
       NVL(PONTO_EXTRA.DTAOPERACAO,NULL),
       NVL(PONTO_EXTRA.vlroperacao,0),
       NVL(INVEST_PRECO.DTAOPERACAO,NULL),
       NVL(INVEST_PRECO.vlroperacao,0),
     --  DESC_ANTEC_FORNEC.DTAOPERACAO,
     --  DESC_ANTEC_FORNEC.vlroperacao,
      NVL(COMP_TITULO_ARECB.DTAOPERACAO,NULL),
      NVL( COMP_TITULO_ARECB.vlroperacao,0)
       
  From FI_TITULO, GE_PESSOA, FI_TITOPERACAO,
  
  /* Cont Fid Desc PAGTO TROCA  716   */
 
  (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (716)
   GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
     )PAGTO_TROCA,       
       
   /* Cont Fid Desc LOGISTICA  710*/     
          
   (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (710)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
   )DESC_LOGISTICA,  


   /* Cont Fid Desc Fidelidade 701 */
 
(SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (701)  
        GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
       )DESC_FIDEL,    
         
 /*  Contrato Fidelidade Aniv 700  */
  
  (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (700)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
     )DESC_ANIVER,   
         
/* Cont Fid Desc Inauguração  703  */
 
  (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (703)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
    )DESC_INAUG,  

         
 /* Cont Fid Desc Intr Produto 708   */
 
  (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (708)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
      )INTR_PRODUTO,
                   
 /* Cont Fid Desc Marketing    711  */
 
  (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao  From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (711)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
     )DESC_MARKETING,   
 
 /* Cont Fid Desc Tabloide     715  */
 
  (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (715)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
      )DESC_TABLOIDE,
         
/* Cont Fid Desc Ponto Extra  712   */
  
 (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (712)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
     )PONTO_EXTRA,  
        
 /* Cont Fid Desc INVEST PRECO 709   */
 
      (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (709)
    GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
     )INVEST_PRECO,  
     
/* DESC_ANTEC_FORNEC SOMA DAS OPERAÇÕES 197 E 138     

     (SELECT MAX(C.DTAOPERACAO),nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (197)
     )
     
      + (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (138)
     )DESC_ANTEC_FORNEC,  */  
       
/* COMP_TITULO_ARECB 19 */         
     
    (SELECT A.NROEMPRESA NROEMPRESA, B.SEQPESSOA SEQPESSOA, A.SEQTITULO SEQTITULO, A.NROTITULO NROTITULO, C.DTAOPERACAO DTAOPERACAO, nvl(sum(c.vlroperacao),0)vlroperacao From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND A.DTAEMISSAO BETWEEN '&DT1' AND '&DT2' --  SELECT * From FI_TITULO A WHERE A.NROTITULO IN (558)
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (19)
      GROUP BY 
   A.NROEMPRESA,
   B.SEQPESSOA, 
   A.SEQTITULO,
   A.NROTITULO,
   C.DTAOPERACAO
 
     )COMP_TITULO_ARECB   
  
       
 Where FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
   AND FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
   AND FI_TITULO.SITUACAO != 'C'
   AND FI_TITOPERACAO.OPCANCELADA IS NULL
   AND FI_TITULO.OBRIGDIREITO = 'O'
   AND FI_TITULO.DTAEMISSAO BETWEEN '&DT1' AND '&DT2'
   AND FI_TITULO.CODESPECIE IN ('DUPP')
   AND FI_TITULO.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND FI_TITOPERACAO.CODOPERACAO IN (700, 701, 703, 708, 709, 710, 711, 712, 715, 716, 19, 197, 138)
   
   AND FI_TITULO.SEQTITULO = PAGTO_TROCA.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = PAGTO_TROCA.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = PAGTO_TROCA.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = PAGTO_TROCA.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = DESC_LOGISTICA.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = DESC_LOGISTICA.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = DESC_LOGISTICA.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = DESC_LOGISTICA.NROEMPRESA(+) 
   AND FI_TITULO.SEQTITULO = DESC_FIDEL.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = DESC_FIDEL.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = DESC_FIDEL.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = DESC_FIDEL.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = DESC_ANIVER.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = DESC_ANIVER.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = DESC_ANIVER.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = DESC_ANIVER.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = DESC_INAUG.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = DESC_INAUG.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = DESC_INAUG.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = DESC_INAUG.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = INTR_PRODUTO.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = INTR_PRODUTO.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = INTR_PRODUTO.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = INTR_PRODUTO.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = DESC_MARKETING.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = DESC_MARKETING.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = DESC_MARKETING.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = DESC_MARKETING.NROEMPRESA(+) 
   AND FI_TITULO.SEQTITULO = DESC_TABLOIDE.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = DESC_TABLOIDE.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = DESC_TABLOIDE.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = DESC_TABLOIDE.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = PONTO_EXTRA.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = PONTO_EXTRA.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = PONTO_EXTRA.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = PONTO_EXTRA.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = INVEST_PRECO.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = INVEST_PRECO.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = INVEST_PRECO.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = INVEST_PRECO.NROEMPRESA (+)
 --  AND FI_TITULO.SEQTITULO = DESC_ANTEC_FORNEC.SEQTITULO(+)
 --  AND GE_PESSOA.SEQPESSOA = DESC_ANTEC_FORNEC.SEQPESSOA (+)
 --  AND FI_TITULO.NROTITULO = DESC_ANTEC_FORNEC.NROTITULO (+)
 --  AND FI_TITULO.NROEMPRESA = DESC_ANTEC_FORNEC.NROEMPRESA (+)
   AND FI_TITULO.SEQTITULO = COMP_TITULO_ARECB.SEQTITULO(+)
   AND GE_PESSOA.SEQPESSOA = COMP_TITULO_ARECB.SEQPESSOA (+)
   AND FI_TITULO.NROTITULO = COMP_TITULO_ARECB.NROTITULO (+)
   AND FI_TITULO.NROEMPRESA = COMP_TITULO_ARECB.NROEMPRESA (+)
 --  AND FI_TITULO.NROTITULO IN (558)
   
   
   
   GROUP BY GE_PESSOA.NOMERAZAO,
            GE_PESSOA.SEQPESSOA,
            GE_PESSOA.NROCGCCPF,
            GE_PESSOA.DIGCGCCPF,
            GE_PESSOA.FISICAJURIDICA,
            PAGTO_TROCA.DTAOPERACAO, 
           PAGTO_TROCA.vlroperacao,
           DESC_LOGISTICA.DTAOPERACAO,
           DESC_LOGISTICA.vlroperacao, 
           DESC_FIDEL.DTAOPERACAO,
           DESC_FIDEL.vlroperacao,
           DESC_ANIVER.DTAOPERACAO,
           DESC_ANIVER.vlroperacao,
           DESC_INAUG.DTAOPERACAO,
           DESC_INAUG.vlroperacao,
           INTR_PRODUTO.DTAOPERACAO,
           INTR_PRODUTO.vlroperacao,
           DESC_MARKETING.DTAOPERACAO,
           DESC_MARKETING.vlroperacao,
           DESC_TABLOIDE.DTAOPERACAO,
           DESC_TABLOIDE.vlroperacao,
           PONTO_EXTRA.DTAOPERACAO,
           PONTO_EXTRA.vlroperacao,
           INVEST_PRECO.DTAOPERACAO,
           INVEST_PRECO.vlroperacao,
         --  DESC_ANTEC_FORNEC.DTAOPERACAO,
         --  DESC_ANTEC_FORNEC.vlroperacao,
           COMP_TITULO_ARECB.DTAOPERACAO,
           COMP_TITULO_ARECB.vlroperacao
 Order By PESSOA










-----------------------------------------------------------------------------------------------
-------------------------------  MOVIMENTOS DE TITULOS OBRIGACAO ------------------------------
-----------------------------------------------------------------------------------------------

Select MAX(FI_TITULO.NROEMPRESA)NROEMPRESA,
       GE_PESSOA.NOMERAZAO PESSOA,
       GE_PESSOA.SEQPESSOA,
       SUBSTR(FC5MASKCNPJCPF(GE_PESSOA.NROCGCCPF,
                             GE_PESSOA.DIGCGCCPF,
                             GE_PESSOA.FISICAJURIDICA),
              1,
              20)CNPJ_CPF,
       MAX(FI_TITOPERACAO.USUALTERACAO)USUALTERACAO,   
       MAX(FI_TITULO.NROTITULO)NROTITULO,
       MAX(FI_TITULO.CODESPECIE)CODESPECIE,
       MAX(TO_CHAR(FI_TITOPERACAO.DTAOPERACAO, 'DD/MM/YYYY'))DTAOPERACAO,
       MAX(TO_CHAR(FI_TITOPERACAO.DTACONTABILIZA, 'DD/MM/YYYY'))DTACONTABILIZACAO,
       MAX(TO_CHAR(FI_TITOPERACAO.DTAALTERACAO, 'DD/MM/YYYY'))DTAALTERACAO,   
       MAX(TO_CHAR(FI_TITULO.DTAVENCIMENTO, 'DD/MM/YYYY'))DTAVENCIMENTO,      
       MAX(TO_CHAR(FI_TITULO.DTAQUITACAO, 'DD/MM/YYYY'))DTAQUITACAO,
       MAX(TO_CHAR(FI_TITULO.DTAPROGRAMADA, 'DD/MM/YYYY'))DTAPROGRAMADA, 
       MAX(FI_TITULO.VLRNOMINAL)VLRNOMINAL,
            
  /* Cont Fid Desc PAGTO TROCA  716   */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (716)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )PAGTO_TROCA,       
       
   /* Cont Fid Desc LOGISTICA  710*/     
          
   (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (710)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
   )DESC_LOGISTICA,

   /* Cont Fid Desc Fidelidade 701 */
 
(SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (701)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
    
       )DESC_FIDEL,    
 
         
 /*  Contrato Fidelidade Aniv 700  */
  
  (SELECT NVL(sum(C.VLROPERACAO),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (700)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_ANIVER,
         
/* Cont Fid Desc Inauguração  703  */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (703)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
    )DESC_INAUG,
         
 /* Cont Fid Desc Intr Produto 708   */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (708)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
      )INTR_PRODUTO,
         
 /* Cont Fid Desc Marketing    711  */
 
  (SELECT nvl(sum(c.vlroperacao),0)  From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (711)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_MARKETING,
         
 /* Cont Fid Desc Tabloide     715  */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (715)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
      )DESC_TABLOIDE,
         
/* Cont Fid Desc Ponto Extra  712   */
  
 (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (712)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )PONTO_EXTRA,
         
 
 /* Cont Fid Desc INVEST PRECO 709   */
 
      (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (709)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
 
     )INVEST_PRECO,  
     
/* DESC_ANTEC_FORNEC SOMA DAS OPERAÇÕES 197 E 138  */     

     (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (197)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     ) + (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (138)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_ANTEC_FORNEC,  
       
/* COMP_TITULO_ARECB 19 */         
     
    (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (19)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
 
     )COMP_TITULO_ARECB   
                          
       
  From FI_TITULO, GE_PESSOA, FI_TITOPERACAO
       
 Where FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
   AND FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
   AND FI_TITULO.SITUACAO != 'C'
   AND FI_TITOPERACAO.OPCANCELADA IS NULL
   AND FI_TITULO.OBRIGDIREITO = 'O'
   AND FI_TITOPERACAO.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND FI_TITULO.CODESPECIE IN ('DUPP')
   AND FI_TITULO.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND FI_TITOPERACAO.CODOPERACAO IN (700, 701, 703, 708, 709, 710, 711, 712, 715, 716, 19, 197, 138)

   GROUP BY GE_PESSOA.NOMERAZAO,
            GE_PESSOA.SEQPESSOA,
            GE_PESSOA.NROCGCCPF,
            GE_PESSOA.DIGCGCCPF,
            GE_PESSOA.FISICAJURIDICA,
            FI_TITULO.SEQTITULO,
            FI_TITULO.NROTITULO,
            FI_TITULO.NROEMPRESA
 Order By PESSOA



-----------------------------------------------------------------------------------------------
---------------  MOVIMENTOS DE TITULOS OBRIGACAO ----- VERSÃO PUBLICADA 04/09 -----------------
-----------------------------------------------------------------------------------------------

Select GE_PESSOA.NOMERAZAO || ' - ' || GE_PESSOA.SEQPESSOA PESSOA,
       SUBSTR(FC5MASKCNPJCPF(GE_PESSOA.NROCGCCPF,
                             GE_PESSOA.DIGCGCCPF,
                             GE_PESSOA.FISICAJURIDICA),
              1,
              20)CNPJ_CPF,
       MAX(FI_TITULO.NROEMPRESA)NROEMPRESA,
       MAX(FI_TITULO.NROTITULO)NROTITULO,
       MAX(FI_TITULO.CODESPECIE)CODESPECIE,
       MAX(TO_CHAR(FI_TITULO.DTAVENCIMENTO, 'DD/MM/YYYY'))DTAVENCIMENTO,
       MAX(TO_CHAR(FI_TITULO.DTAQUITACAO, 'DD/MM/YYYY'))DTAQUITACAO,
       MAX(FI_TITULO.VLRNOMINAL)VLRNOMINAL,
       MAX(FI_TITULO.VLRPAGO)VLRPAGO,
            
  /* Cont Fid Desc PAGTO TROCA  716   */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (716)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )PAGTO_TROCA,       
       
   /* Cont Fid Desc LOGISTICA  710*/     
          
   (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (710)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
   )DESC_LOGISTICA,

   /* Cont Fid Desc Fidelidade 701 */
 
(SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (701)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
    
       )DESC_FIDEL,    
 
         
 /*  Contrato Fidelidade Aniv 700  */
  
  (SELECT NVL(sum(C.VLROPERACAO),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (700)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_ANIVER,
         
/* Cont Fid Desc Inauguração  703  */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (703)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
    )DESC_INAUG,
         
 /* Cont Fid Desc Intr Produto 708   */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (708)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
      )INTR_PRODUTO,
         
 /* Cont Fid Desc Marketing    711  */
 
  (SELECT nvl(sum(c.vlroperacao),0)  From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (711)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_MARKETING,
         
 /* Cont Fid Desc Tabloide     715  */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (715)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
      )DESC_TABLOIDE,
         
/* Cont Fid Desc Ponto Extra  712   */
  
 (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (712)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )PONTO_EXTRA,
         
 
 /* Cont Fid Desc INVEST PRECO 709   */
 
      (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (709)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
 
     )INVEST_PRECO,  
       
       MAX(TO_CHAR(FI_TITOPERACAO.DTACONTABILIZA, 'DD/MM/YYYY'))DTACONTABILIZACAO,
       MAX(TO_CHAR(FI_TITOPERACAO.DTAALTERACAO, 'DD/MM/YYYY'))DTAALTERACAO,
       MAX(FI_TITOPERACAO.USUALTERACAO)USUALTERACAO,      
       MAX(TO_CHAR(FI_TITULO.DTAPROGRAMADA, 'DD/MM/YYYY'))DTAPROGRAMADA,
  
 /*  OPERACAO 6 (TOTAL - DESCONTOS) VALOR PAGO   */ 
   CASE
         WHEN (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
               Where A.SEQTITULO = C.SEQTITULO
                 AND A.SEQPESSOA = B.SEQPESSOA
                 AND A.SITUACAO != 'C'
                 AND C.OPCANCELADA IS NULL
                 AND A.OBRIGDIREITO = 'O'
                 AND A.CODESPECIE IN ('DUPP')
                 AND A.NROEMPRESA IN
                     (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
                 AND C.CODOPERACAO IN (6)
                 AND A.SEQTITULO = FI_TITULO.SEQTITULO
                 AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
                 AND A.NROTITULO = FI_TITULO.NROTITULO
                 AND A.NROEMPRESA = FI_TITULO.NROEMPRESA) = 0 
          THEN
                 MAX(FI_TITULO.VLRPAGO)
          ELSE
                (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
                 Where A.SEQTITULO = C.SEQTITULO
                   AND A.SEQPESSOA = B.SEQPESSOA
                   AND A.SITUACAO != 'C'
                   AND C.OPCANCELADA IS NULL
                   AND A.OBRIGDIREITO = 'O'
                   AND A.CODESPECIE IN ('DUPP')
                   AND A.NROEMPRESA IN
                       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
                   AND C.CODOPERACAO IN (6)
                      AND A.SEQTITULO = FI_TITULO.SEQTITULO
                   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
                   AND A.NROTITULO = FI_TITULO.NROTITULO
                   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA )
                       END VALOR_PAGO 
                          
 
      
       
       
  From FI_TITULO, GE_PESSOA, FI_TITOPERACAO
       
 Where FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
   AND FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
   AND FI_TITULO.SITUACAO != 'C'
   AND FI_TITOPERACAO.OPCANCELADA IS NULL
   AND FI_TITULO.OBRIGDIREITO = 'O'
   AND FI_TITOPERACAO.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND FI_TITULO.CODESPECIE IN ('DUPP')
   AND FI_TITULO.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND FI_TITOPERACAO.CODOPERACAO IN (700, 701, 703, 708, 709, 710, 711, 712, 715, 716)

   GROUP BY GE_PESSOA.NOMERAZAO,
            GE_PESSOA.SEQPESSOA,
            GE_PESSOA.NROCGCCPF,
            GE_PESSOA.DIGCGCCPF,
            GE_PESSOA.FISICAJURIDICA,
            FI_TITULO.SEQTITULO,
            FI_TITULO.NROTITULO,
            FI_TITULO.NROEMPRESA
 Order By PESSOA

------------------------------------------------------------------------------------
SELECT * FROM FI_TITOPERACAO
WHERE SEQTITULO IN (1090255515)


SELECT * FROM FI_TITULO--   38177       SEQTITULO  1090255515 --  NROTITULO 27511
WHERE NROTITULO IN      (31206,31324,31456,31508,31888)
AND SEQPESSOA IN (49077)

--------------------------------------------------------------------------------------



  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
  -- AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (138)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_ANTEC_FORNEC,  
     

















----------------------------------------------------------------------------------------------------

CASE
         WHEN (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
  -- AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (6)
 --  AND NROTITULO IN (43080)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
         
         
            = 0 THEN
          MAX(FI_TITULO.VLRPAGO)VLRPAGO
         ELSE
          (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
  -- AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (6)
 --  AND NROTITULO IN (43080)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
       END  )PAGTO_CONTA 


----------------------------------------------------------------------------------------------------------
---------------  MOVIMENTOS DE TITULOS OBRIGACAO ----- VERSÃO PUBLICADA 04/09 ------  Atualizada 16:00 ---
----------------------------------------------------------------------------------------------------------

Select MAX(FI_TITULO.NROEMPRESA)NROEMPRESA,
       GE_PESSOA.NOMERAZAO PESSOA,
       GE_PESSOA.SEQPESSOA,
       SUBSTR(FC5MASKCNPJCPF(GE_PESSOA.NROCGCCPF,
                             GE_PESSOA.DIGCGCCPF,
                             GE_PESSOA.FISICAJURIDICA),
              1,
              20)CNPJ_CPF,
       MAX(FI_TITOPERACAO.USUALTERACAO)USUALTERACAO,   
       MAX(FI_TITULO.NROTITULO)NROTITULO,
       MAX(FI_TITULO.CODESPECIE)CODESPECIE,
       MAX(TO_CHAR(FI_TITOPERACAO.DTAOPERACAO, 'DD/MM/YYYY'))DTAOPERACAO,
       MAX(TO_CHAR(FI_TITOPERACAO.DTACONTABILIZA, 'DD/MM/YYYY'))DTACONTABILIZACAO,
       MAX(TO_CHAR(FI_TITOPERACAO.DTAALTERACAO, 'DD/MM/YYYY'))DTAALTERACAO,   
       MAX(TO_CHAR(FI_TITULO.DTAVENCIMENTO, 'DD/MM/YYYY'))DTAVENCIMENTO,      
       MAX(TO_CHAR(FI_TITULO.DTAQUITACAO, 'DD/MM/YYYY'))DTAQUITACAO,
       MAX(TO_CHAR(FI_TITULO.DTAPROGRAMADA, 'DD/MM/YYYY'))DTAPROGRAMADA, 
       MAX(FI_TITULO.VLRNOMINAL)VLRNOMINAL,
            
  /* Cont Fid Desc PAGTO TROCA  716   */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (716)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )PAGTO_TROCA,       
       
   /* Cont Fid Desc LOGISTICA  710*/     
          
   (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (710)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
   )DESC_LOGISTICA,

   /* Cont Fid Desc Fidelidade 701 */
 
(SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (701)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
    
       )DESC_FIDEL,    
 
         
 /*  Contrato Fidelidade Aniv 700  */
  
  (SELECT NVL(sum(C.VLROPERACAO),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (700)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_ANIVER,
         
/* Cont Fid Desc Inauguração  703  */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (703)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
    )DESC_INAUG,
         
 /* Cont Fid Desc Intr Produto 708   */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (708)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
      )INTR_PRODUTO,
         
 /* Cont Fid Desc Marketing    711  */
 
  (SELECT nvl(sum(c.vlroperacao),0)  From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (711)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_MARKETING,
         
 /* Cont Fid Desc Tabloide     715  */
 
  (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (715)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
      )DESC_TABLOIDE,
         
/* Cont Fid Desc Ponto Extra  712   */
  
 (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (712)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )PONTO_EXTRA,
         
 
 /* Cont Fid Desc INVEST PRECO 709   */
 
      (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (709)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
 
     )INVEST_PRECO,  
       
/* DESC_ANTEC_FORNEC SOMA DAS OPERAÇÕES 197 E 138  */     

     (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (197)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     ) + (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (138)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
     )DESC_ANTEC_FORNEC,  
       
/* COMP_TITULO_ARECB 19 */         
     
    (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
   AND C.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (19)
   AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
 
     )COMP_TITULO_ARECB   
                          
      
    From FI_TITULO, GE_PESSOA, FI_TITOPERACAO
       
 Where FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
   AND FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
   AND FI_TITULO.SITUACAO != 'C'
   AND FI_TITOPERACAO.OPCANCELADA IS NULL
   AND FI_TITULO.OBRIGDIREITO = 'O'
   AND FI_TITOPERACAO.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND FI_TITULO.CODESPECIE IN ('DUPP')
   AND FI_TITULO.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND FI_TITOPERACAO.CODOPERACAO IN (700, 701, 703, 708, 709, 710, 711, 712, 715, 716, 19, 197, 138)

   GROUP BY GE_PESSOA.NOMERAZAO,
            GE_PESSOA.SEQPESSOA,
            GE_PESSOA.NROCGCCPF,
            GE_PESSOA.DIGCGCCPF,
            GE_PESSOA.FISICAJURIDICA,
            FI_TITULO.SEQTITULO,
            FI_TITULO.NROTITULO,
            FI_TITULO.NROEMPRESA
 Order By PESSOA

 
   
                       
 
 -------------------------------------------------------------------------------------------------------------------------     
       
       
  From FI_TITULO, GE_PESSOA, FI_TITOPERACAO
       
 Where FI_TITULO.SEQTITULO = FI_TITOPERACAO.SEQTITULO
   AND FI_TITULO.SEQPESSOA = GE_PESSOA.SEQPESSOA
   AND FI_TITULO.SITUACAO != 'C'
   AND FI_TITOPERACAO.OPCANCELADA IS NULL
   AND FI_TITULO.OBRIGDIREITO = 'O'
   AND FI_TITOPERACAO.DTAOPERACAO BETWEEN '#DT1' AND '#DT2'
   AND FI_TITULO.CODESPECIE IN ('DUPP')
   AND FI_TITULO.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND FI_TITOPERACAO.CODOPERACAO IN (700, 701, 703, 708, 709, 710, 711, 712, 715, 716)

   GROUP BY GE_PESSOA.NOMERAZAO,
            GE_PESSOA.SEQPESSOA,
            GE_PESSOA.NROCGCCPF,
            GE_PESSOA.DIGCGCCPF,
            GE_PESSOA.FISICAJURIDICA,
            FI_TITULO.SEQTITULO,
            FI_TITULO.NROTITULO,
            FI_TITULO.NROEMPRESA
 Order By PESSOA

------------------------------------------------------------------------------------
SELECT * FROM FI_TITOPERACAO
WHERE SEQTITULO IN (1231244175,1231419710,1238391339,1242874827)


SELECT * FROM FI_TITULO--   38177         
WHERE NROTITULO IN      (42589, 42568, 270545, 270701)
AND SEQPESSOA IN (38177, 18138)


----------------------------------------------------------------------------------------------------

CASE
         WHEN (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
  -- AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (6)
 --  AND NROTITULO IN (43080)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
         
         
            = 0 THEN
          MAX(FI_TITULO.VLRPAGO)VLRPAGO
         ELSE
          (SELECT nvl(sum(c.vlroperacao),0) From FI_TITULO A, GE_PESSOA B, FI_TITOPERACAO C
 Where A.SEQTITULO = C.SEQTITULO
   AND A.SEQPESSOA = B.SEQPESSOA
   AND A.SITUACAO != 'C'
   AND C.OPCANCELADA IS NULL
   AND A.OBRIGDIREITO = 'O'
  -- AND C.DTAOPERACAO BETWEEN '&DT1' AND '&DT2'
   AND A.CODESPECIE IN ('DUPP')
   AND A.NROEMPRESA IN
       (1, 12, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 32, 33, 34)
   AND C.CODOPERACAO IN (6)
 --  AND NROTITULO IN (43080)
      AND A.SEQTITULO = FI_TITULO.SEQTITULO
   AND B.SEQPESSOA = GE_PESSOA.SEQPESSOA  
   AND A.NROTITULO = FI_TITULO.NROTITULO
   AND A.NROEMPRESA = FI_TITULO.NROEMPRESA
       END  )PAGTO_CONTA 

