Select GE_EMPRESA.NROEMPRESA,
       FI_CTACORRENTE.SEQCTACORRENTE,
       FI_CTACORRENTE.DESCRICAO,
       FI_CTACORLANCA.NRODOCUMENTO,
       FI_CTACORLANCA.SERIEDOCUMENTO,
       FI_CTACORLANCA.DTALANCTO,
       FI_OPERACAO.CODOPERACAO,
       FI_OPERACAO.DESCRICAO,
       FI_CTACORCONC.DTACONCILIACAO,
       FI_CTACORCONC.DTACOMPENSACAO, 
       FI_CTACORLANCA.HISTORICO,
       FI_CTACORCONC.CONCILIADO,
       FI_CTACORLANCA.VLRLANCAMENTO,
       FI_CTACORLANCA.TIPOLANCTO
       
       
  From FI_CTACORLANCA,
       FI_CTACORRENTE,
       FI_GRUPOCONTACORRENTE,
       GE_EMPRESA,
       FI_OPERACAO,
       FI_CTACORCONC 
 Where FI_CTACORLANCA.SEQCTACORRENTE(+) = FI_CTACORRENTE.SEQCTACORRENTE
   AND FI_CTACORRENTE.SEQGRUPO = FI_GRUPOCONTACORRENTE.SEQGRUPO(+)
   AND FI_CTACORLANCA.NROEMPRESAMAE(+) = '2'
   AND FI_CTACORLANCA.SEQLANCTO = FI_CTACORCONC.SEQLANCTO (+)
   AND FI_CTACORRENTE.NROEMPRESAMAE = '2'
   AND FI_CTACORLANCA.CODOPERACAO = FI_OPERACAO.CODOPERACAO(+)
   AND GE_EMPRESA.NROEMPRESA = FI_CTACORRENTE.NROEMPRESA
   AND GE_EMPRESA.STATUS = 'A'
   AND DTALANCTO BETWEEN '01-jan-1990' AND '23-nov-2023'
   AND FI_CTACORRENTE.SEQCTACORRENTE IN ('462')  
           
   AND FI_CTACORRENTE.TIPOCONTA = 'T'
   AND OPCANCELADA(+) IS NULL
   AND TIPOLANCTO(+) != 'H'
   AND FI_CTACORRENTE.SITUACAO = 'A'
 Order By FI_GRUPOCONTACORRENTE.DESCRICAO,
          FI_CTACORRENTE.DESCRICAO || ' - ' ||
          FI_CTACORRENTE.SEQCTACORRENTE,
          FI_CTACORLANCA.DTALANCTO


 ---------------------------------------------------------------------------------
 
 ALTER SESSION SET NLS_DATE_FORMAT = 'DD/MM/YYYY HH24:MI:SS';

 Select GE_EMPRESA.NROEMPRESA,
       FI_CTACORRENTE.SEQCTACORRENTE,
       FI_CTACORRENTE.DESCRICAO,
       FI_CTACORLANCA.NRODOCUMENTO,
       FI_CTACORLANCA.SERIEDOCUMENTO,
       TO_CHAR(FI_CTACORLANCA.DTALANCTO, 'DD/MM/YYYY')DTALANCTO,
       FI_OPERACAO.CODOPERACAO,
       FI_OPERACAO.DESCRICAO,
       TO_CHAR(FI_CTACORCONC.DTACONCILIACAO, 'DD/MM/YYYY')DTACONCILIACAO,
       TO_CHAR(FI_CTACORCONC.DTACOMPENSACAO, 'DD/MM/YYYY')DTACOMPENSACAO,
       FI_CTACORLANCA.HISTORICO,
       FI_CTACORCONC.CONCILIADO,
       FI_CTACORLANCA.VLRLANCAMENTO,
       FI_CTACORLANCA.TIPOLANCTO
       
       
  From FI_CTACORLANCA,
       FI_CTACORRENTE,
       FI_GRUPOCONTACORRENTE,
       GE_EMPRESA,
       FI_OPERACAO,
       FI_CTACORCONC 
 Where FI_CTACORLANCA.SEQCTACORRENTE(+) = FI_CTACORRENTE.SEQCTACORRENTE
   AND FI_CTACORRENTE.SEQGRUPO = FI_GRUPOCONTACORRENTE.SEQGRUPO(+)
   AND FI_CTACORLANCA.NROEMPRESAMAE(+) = '2'
   AND FI_CTACORLANCA.SEQLANCTO = FI_CTACORCONC.SEQLANCTO (+)
   AND FI_CTACORRENTE.NROEMPRESAMAE = '2'
   AND FI_CTACORLANCA.CODOPERACAO = FI_OPERACAO.CODOPERACAO(+)
   AND GE_EMPRESA.NROEMPRESA = FI_CTACORRENTE.NROEMPRESA
   AND GE_EMPRESA.STATUS = 'A'
   AND DTALANCTO BETWEEN '#DT1' AND '#DT2'
   AND FI_CTACORRENTE.SEQCTACORRENTE IN ('462')  
           
   AND FI_CTACORRENTE.TIPOCONTA = 'T'
   AND OPCANCELADA(+) IS NULL
   AND TIPOLANCTO(+) != 'H'
   AND FI_CTACORRENTE.SITUACAO = 'A'
 Order By FI_GRUPOCONTACORRENTE.DESCRICAO,
          FI_CTACORRENTE.DESCRICAO || ' - ' ||
          FI_CTACORRENTE.SEQCTACORRENTE,
          FI_CTACORLANCA.DTALANCTO

 
 
 
 
 ------------------------------------------------------------------------------------

 
 select * from all_all_tables
 where table_name like '%ACUM%'
 
select * from VERAN_CATEGORIA VC
where vc.COD5 in (151, 152) 


select * from MRL_CUSTODIA Y
where y.seqproduto in (1829327)
and dtaentradasaida = '14-nov-2023'

select * from MAP_PRODUTO A
where a.seqproduto in (1829327)

select * from MAP_FAMDIVISAO D
where seqfamilia in (220025)

SELECT * FROM MAP_FAMEMBALAGEM K
where seqfamilia in (220025)

SELECT * FROM MAP_FAMDIVCATEG
where seqfamilia in (220025)

select * from MAX_COMPRADOR
where seqcomprador in (40)

select * from MAP_CATEGORIA
where seqcategoria in (151, 152)
and tipcategoria = 'L' 

select * from VERAN_CATEGORIA VC
where vc.COD1 in (151, 152)

select * from MRL_CUSTODIA Y,(SELECT * FROM
                     MAXV_ABCDISTRIBBASE V
                     WHERE V.nroformapagto NOT IN (68, 73)), MAX_COMPRADOR CP, MAP_PRODUTO A, MAP_FAMDIVISAO D, MAP_FAMDIVCATEG FD, MAP_PRODUTO PB, MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E, MAX_DIVISAO DV, MAP_PRODACRESCCUSTORELAC PR, MRLV_DESCONTOREGRA RE,
WHERE D.seqfamilia in (220025)
AND PB.SEQPRODUTO IN ( 1829327)
AND PB.SEQFAMILIA = D.SEQFAMILIA
AND D.SEQFAMILIA = FD.SEQFAMILIA

--------------------------------------------------------------------------------------------------------------------------------
------------------------------------------- Versão atual -----------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------


select /*+OPTIMIZER_FEATURES_ENABLE('10.2.0.4')*/  
V.NROEMPRESA,

TO_CHAR(V.dtavda, 'DD/MM/YYYY') DIA_MES,

sum( V.QTDITEM / K.QTDEMBALAGEM )
as QUANTIDADE,

V.vlritem,

sum( ( round( V.VLRITEM, 2 ) ) )
as VLRVENDANORMAL,

sum( 
( ( (Y.CMDIAVLRNF ) + Y.CMDIAIPI - Y.CMDIACREDICMS - nvl( Y.CMDIACREDPIS, 0 ) - nvl( Y.CMDIACREDCOFINS, 0 ) - nvl( Y.CMDIACREDIPI, 0 ) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF ) 

*
 CASE WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL THEN 
 COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1))
 ELSE 
 1
 END

*
DECODE('S', 'N', 1, NVL( a.propqtdprodutobase, 1) )
- ( decode( Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL( a.propqtdprodutobase, 1 ) /
 DECODE(NVL(Y.QTDVDA,0), 0, Y.QTDVERBAVDA, Y.QTDVDA) ) )
+ decode (V.ACMCOMPRAVENDA,'N', 0,
 decode( 'N', 'S', 0,
 ( decode( nvl( Y.VLRVERBAVDAACR, 0 ), 0, 0, Y.VLRVERBAVDAACR * NVL( a.propqtdprodutobase, 1 ) /
 DECODE(NVL(Y.QTDVDA,0), 0, 1, Y.QTDVDA) ) ) )
 ) )
 * (V.QTDITEM))
as VLRCTOLIQVDA,


sum( 
( decode( Y.QTDVERBAVDA, 0, 0,
 ( Y.VLRVERBAVDA - nvl( Y.VLRverbaVDAindevida, 0 ) )
 * nvl( a.propqtdprodutobase, 1 )
 / Y.QTDVDA )
)
*
( V.QTDITEM ) ) 
as VLRVERBA,

sum(
decode( V.ACMCOMPRAVENDA, 'I', ( V.VLRITEM * ( V.PERCPMF + V.PEROUTROIMPOSTO ) / 100 ), 
 decode( Y.QTDVDA * V.QTDITEM, 0, 0, ( Y.VLRIMPOSTOVDA - nvl( Y.VLRIPIVDA, 0 ) ) * DECODE('S','N',1, NVL( a.propqtdprodutobase, 1) ) / Y.QTDVDA * V.QTDITEM ) )
+ decode( V.ACMCOMPRAVENDA, 'I', 0, 
 decode( V.ICMSEFETIVOITEM, 0, V.ICMSITEM, V.ICMSEFETIVOITEM ) 
 + V.VLRFCPICMS + V.PISITEM + V.COFINSITEM )
) 
as VLRIMPOSTOVDA,

CP.APELIDO COMPRADOR,

VC.COD1,
VC.NIVEL1,
VC.COD2,
VC.NIVEL2,

sum( V.ICMSITEM )
as VLRICMS,

sum( V.PISITEM )
as VLRPIS,

sum( V.COFINSITEM )
as VLRCOFINS

from MRL_CUSTODIA Y, (SELECT * FROM
                     MAXV_ABCDISTRIBBASE V
                     WHERE V.nroformapagto NOT IN (68, 73)) V, MAX_COMPRADOR CP, MAP_PRODUTO A, MAP_PRODUTO PB, MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E, MAX_DIVISAO DV, MAP_PRODACRESCCUSTORELAC PR, MRLV_DESCONTOREGRA RE,
VERAN_CATEGORIA VC, MAP_FAMDIVCATEG FD 
where D.SEQFAMILIA = A.SEQFAMILIA
and D.NRODIVISAO = V.NRODIVISAO
and V.SEQPRODUTO = A.SEQPRODUTO
and V.SEQPRODUTOCUSTO = PB.SEQPRODUTO
and V.NROEMPRESA IN (2)---(2,3,4,5,6,7,8,9,10,11,12,32,33,34)
--and V.NROSEGMENTO in ( 3,8,9,2,12,14,13,1,11 )
and V.NRODIVISAO = D.NRODIVISAO
and E.NROEMPRESA = V.NROEMPRESA
and E.NRODIVISAO = DV.NRODIVISAO
AND V.SEQPRODUTO = PR.SEQPRODUTO(+)
AND V.DTAVDA = PR.DTAMOVIMENTACAO(+)
AND CP.SEQCOMPRADOR = D.SEQCOMPRADOR
AND D.SEQFAMILIA = FD.SEQFAMILIA
AND E.NRODIVISAO = FD.NRODIVISAO
AND FD.SEQCATEGORIA = VC.COD5(+)
AND Y.DTAENTRADASAIDA = '14-NOV-2023'
AND FD.STATUS='A'
--and Y.DTAENTRADASAIDA BETWEEN (TRUNC(LAST_DAY(SYSDATE-1)) - TO_CHAR(TRUNC(LAST_DAY(SYSDATE-1)), 'DD') + 1) AND TRUNC(SYSDATE-1)
and Y.NROEMPRESA = nvl( E.NROEMPCUSTOABC, E.NROEMPRESA ) 
and Y.DTAENTRADASAIDA = V.DTAVDA
 and K.SEQFAMILIA = A.SEQFAMILIA and K.QTDEMBALAGEM = 1 AND V.SEQPRODUTO = RE.SEQPRODUTO (+) 
AND V.DTAVDA = RE.DATAFATURAMENTO (+)
AND V.NRODOCTO = RE.NUMERODF (+)
AND V.SERIEDOCTO = RE.SERIEDF (+) 
AND V.NROEMPRESA = RE.NROEMPRESA (+) 
and Y.SEQPRODUTO = PB.SEQPRODUTO
AND Y.SEQPRODUTO IN (1829327)
and V.QTDITEM != 0
and DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) in ( 'S', 'I' ) 
and V.CODGERALOPER <> 517
and V.CODGERALOPER = 309


group by CP.APELIDO,
V.NROEMPRESA,
TO_CHAR(V.dtavda, 'DD/MM/YYYY'),
VC.COD1,
VC.NIVEL1,
VC.COD2,
VC.NIVEL2,
V.vlritem
 




 
---------------------------------------------------------------------------------------------------------------------------------
 
 (SELECT * FROM
                     MAXV_ABCDISTRIBBASE V
                     WHERE V.nroformapagto NOT IN (68, 73)
                     AND V.seqproduto IN (1829327)
                    -- and v.nrodocto in (855873)
                     and v.dtavda =  '14-nov-2023' 
                     and v.nroempresa in (2)                    
                     
                     
                     )   V                                                                                                     
-------------------------------------------------------------------------------------------- 
 
SELECT A.NROEMPRESA, A.DTAENTRADASAIDA, SUM(VLRVENDA)
  FROM VERAN_TB_FLASHVENDAACUM A 
  WHERE A.DTAENTRADASAIDA BETWEEN '01-NOV-2023' AND '29-NOV-2023'
  GROUP BY A.NROEMPRESA, A.DTAENTRADASAIDA
  ORDER BY 2
  
--------------------------------------------------------------------------------------------
  
   
SELECT B.DESCCOMPLETA, A.* 
  FROM VERAN_TB_FLASHVENDAACUM A, MAP_PRODUTO B 
  WHERE A.DTAENTRADASAIDA = '14-NOV-2023'
  AND B.SEQPRODUTO = A.SEQPRODUTO
  and a.nroempresa in (2)
  AND B.DESCCOMPLETA LIKE '%INAT%'
  --GROUP BY A.NROEMPRESA, A.DTAENTRADASAIDA
  ORDER BY 2
  
 
FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 1, 'M') NIVEL1,
FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 2, 'M') NIVEL2,
FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 3, 'M') NIVEL3,
FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 4, 'M') NIVEL4,
FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 5, 'M') NIVEL5,




--------------------------------------------------------------------------------------------
----------------------- AJUSTADO 30/11 -- VENDA LOJAS  -------------------------------------
--------------------------------------------------------------------------------------------

select /*+OPTIMIZER_FEATURES_ENABLE('10.2.0.4')*/  
V.NROEMPRESA,

TO_CHAR(V.dtavda, 'DD/MM/YYYY') DIA_MES,

sum( V.QTDITEM / K.QTDEMBALAGEM )
as QUANTIDADE,
sum(  (round(V.VLRITEM,2))) 
as VLRVENDANORMAL,

sum( 
( ( (Y.CMDIAVLRNF ) + Y.CMDIAIPI - Y.CMDIACREDICMS - nvl( Y.CMDIACREDPIS, 0 ) - nvl( Y.CMDIACREDCOFINS, 0 ) - nvl( Y.CMDIACREDIPI, 0 ) + Y.CMDIAICMSST + Y.CMDIADESPNF + Y.CMDIADESPFORANF - Y.CMDIADCTOFORANF ) 

*
 CASE WHEN DV.UTILACRESCCUSTPRODRELAC = 'S' AND NVL(A.SEQPRODUTOBASE, A.SEQPRODUTOBASEANTIGO) IS NOT NULL THEN 
 COALESCE(PR.PERCACRESCCUSTORELACVIG, NVL(F_RETACRESCCUSTORELACABC(V.SEQPRODUTO, V.DTAVDA), 1))
 ELSE 
 1
 END

*
DECODE('S', 'N', 1, NVL( a.propqtdprodutobase, 1) )
- ( decode( Y.QTDVERBAVDA, 0, 0, Y.VLRVERBAVDA * NVL( a.propqtdprodutobase, 1 ) /
 DECODE(NVL(Y.QTDVDA,0), 0, Y.QTDVERBAVDA, Y.QTDVDA) ) )
+ decode (V.ACMCOMPRAVENDA,'N', 0,
 decode( 'N', 'S', 0,
 ( decode( nvl( Y.VLRVERBAVDAACR, 0 ), 0, 0, Y.VLRVERBAVDAACR * NVL( a.propqtdprodutobase, 1 ) /
 DECODE(NVL(Y.QTDVDA,0), 0, 1, Y.QTDVDA) ) ) )
 ) )
 * (V.QTDITEM))
as VLRCTOLIQVDA,


sum( 
( decode( Y.QTDVERBAVDA, 0, 0,
 ( Y.VLRVERBAVDA - nvl( Y.VLRverbaVDAindevida, 0 ) )
 * nvl( a.propqtdprodutobase, 1 )
 / Y.QTDVDA )
)
*
( V.QTDITEM ) ) 
as VLRVERBA,

sum(
decode( V.ACMCOMPRAVENDA, 'I', ( V.VLRITEM * ( V.PERCPMF + V.PEROUTROIMPOSTO ) / 100 ), 
 decode( Y.QTDVDA * V.QTDITEM, 0, 0, ( Y.VLRIMPOSTOVDA - nvl( Y.VLRIPIVDA, 0 ) ) * DECODE('S','N',1, NVL( a.propqtdprodutobase, 1) ) / Y.QTDVDA * V.QTDITEM ) )
+ decode( V.ACMCOMPRAVENDA, 'I', 0, 
 decode( V.ICMSEFETIVOITEM, 0, V.ICMSITEM, V.ICMSEFETIVOITEM ) 
 + V.VLRFCPICMS + V.PISITEM + V.COFINSITEM )
) 
as VLRIMPOSTOVDA,

CP.APELIDO COMPRADOR,

--VC.COD1,
--VC.NIVEL1,
--VC.COD2,
--VC.NIVEL2,


NVL(FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 1, 'M'),0) NIVEL1,
NVL(FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 2, 'M'),0) NIVEL2,
--NVL(FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 3, 'M'),0) NIVEL3,
---NVL(FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 4, 'M'),0) NIVEL4,
---NVL(FCATEGORIAFAMILIANIVEL(A.SEQFAMILIA, 1, 5, 'M'),0) NIVEL5,


sum( V.ICMSITEM )
as VLRICMS,

sum( V.PISITEM )
as VLRPIS,

sum( V.COFINSITEM )
as VLRCOFINS

--FD.SEQCATEGORIA

from MRL_CUSTODIA Y, (SELECT * FROM
                     MAXV_ABCDISTRIBBASE V
                     WHERE V.nroformapagto NOT IN (68, 73)) V, MAX_COMPRADOR CP, MAP_PRODUTO A, MAP_PRODUTO PB, MAP_FAMDIVISAO D, MAP_FAMEMBALAGEM K, MAX_EMPRESA E, MAX_DIVISAO DV, MAP_PRODACRESCCUSTORELAC PR, MRLV_DESCONTOREGRA RE
-- MAP_FAMDIVCATEG FD --VERAN_CATEGORIA VC,
where D.SEQFAMILIA = A.SEQFAMILIA
and D.NRODIVISAO = V.NRODIVISAO
and V.SEQPRODUTO = A.SEQPRODUTO
and V.SEQPRODUTOCUSTO = PB.SEQPRODUTO
and V.NROEMPRESA IN (2,3,4,5,6,7,8,9,10,11,12,32,33,34)
and V.NROSEGMENTO in ( 3,8,9,2,12,14,13,1,11 )
and V.NRODIVISAO = D.NRODIVISAO
and E.NROEMPRESA = V.NROEMPRESA
and E.NRODIVISAO = DV.NRODIVISAO
AND V.SEQPRODUTO = PR.SEQPRODUTO(+)
AND V.DTAVDA = PR.DTAMOVIMENTACAO(+)
AND CP.SEQCOMPRADOR = D.SEQCOMPRADOR
--and Y.DTAENTRADASAIDA BETWEEN '14-nov-2023' and '14-nov-2023'
and Y.DTAENTRADASAIDA BETWEEN (TRUNC(LAST_DAY(SYSDATE-1)) - TO_CHAR(TRUNC(LAST_DAY(SYSDATE-1)), 'DD') + 1) AND TRUNC(SYSDATE-1)
and Y.NROEMPRESA = nvl( E.NROEMPCUSTOABC, E.NROEMPRESA ) 
and Y.DTAENTRADASAIDA = V.DTAVDA
 and K.SEQFAMILIA = A.SEQFAMILIA
  and K.QTDEMBALAGEM = 1
  AND V.SEQPRODUTO = RE.SEQPRODUTO (+) 
AND V.DTAVDA = RE.DATAFATURAMENTO (+)
AND V.NRODOCTO = RE.NUMERODF (+)
AND V.SERIEDOCTO = RE.SERIEDF (+) 
AND V.NROEMPRESA = RE.NROEMPRESA (+) 
and Y.SEQPRODUTO = PB.SEQPRODUTO
--and a.seqproduto in (1829327) --, 1829343)

and V.QTDITEM != 0
and DECODE(V.TIPTABELA, 'S', V.CGOACMCOMPRAVENDA, V.ACMCOMPRAVENDA) in ( 'S', 'I' ) 
and V.CODGERALOPER <> 517
and V.CODGERALOPER = 309
 

group by CP.APELIDO,
V.NROEMPRESA,
TO_CHAR(V.dtavda, 'DD/MM/YYYY'),
A.SEQFAMILIA
